### ISSUE TITLE
Getting TypeError: cb is not a function

### ISSUE THREAD

**Issue by L-K-Mist** [hlfshell/serial-synapse#2]
Hi hlfshell,

I'm delighted that someone is tackling a way to interface arduino with node, in a different way to Johnny-five. In fact, I see this approach as a coming gamechanger for all makers who learned arduino first I'm keen to contribute something to this code, like a super-simple example for noobies with noobie-commenting throughout the code. Then an example from how I intend to use this: control several heater modules (like for precision distilling) from an attached laptop.

I'm having some difficulty getting any of the examples to actually work. gone down to a very simple example, but get this error, is this something you've seen before?

```
C:\Users\Dylan\serial-synapse>node index
Serial port connection is closed, so command can not be sent
C:\Users\Dylan\serial-synapse\node_modules\serial-synapse\index.js:130
                        if(!self._conn.isOpen()) return cb("Serial port connection is closed, so command can not be sent");
                                                        ^

TypeError: cb is not a function
    at Synapse._executeCommand (C:\Users\Dylan\serial-synapse\node_modules\serial-synapse\index.js:130:36)
    at Synapse.self.(anonymous function) [as getTemps] (C:\Users\Dylan\serial-synapse\node_modules\serial-synapse\index.js:66:44)
    at Object.<anonymous> (C:\Users\Dylan\serial-synapse\index.js:35:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

C:\Users\Dylan\serial-synapse>
```

**Comment by hlfshell** [comment]
Can you show me the code you're using to use serial-synapse?

**Comment by L-K-Mist** [comment]
# index.js
```
var SerialSynapse = require("serial-synapse");
var SerialPort = require("serialport").SerialPort;
var parsers = require('serialport').parsers;

var arduino = new SerialSynapse();

// arduino.addUpdateHandler(
// {
// 	name: 'getTemps',
// 	identifier: 0,
// 	returns: ["temp1"],
// 	then: function(data){
// 		console.log(("The Temp of area1 is: ") + (data.temp1));
// 	}
// }
// );

arduino.addCommand({
    name: 'getTemps',
    identifier: 0,
    returns: ['temp1']
});


arduino.connection = new SerialPort("COM33", {
    baudrate: 9600,
    parser: parsers.readline('\n\r')
});


arduino.getTemps(function (data) {
    console.log(data);
});

arduino.getTemps();
```


# arduino.ino
```
 #include <CmdMessenger.h>

CmdMessenger cmdMessenger = CmdMessenger(Serial);

enum
{
  kSendTemps,

};

void cmdSetup() {
  cmdMessenger.printLfCr();
  cmdMessenger.attach(kSendTemps, onSendTemps);
}


void setup()
{
  commsSetup();
  // Adds newline to every command
  cmdSetup();

void establishContact() {
  while (Serial.available() <= 0) {
    Serial.println("A1");   // send an initial string
    delay(300);
  }
}

void commsSetup() {
  Serial.begin(9600);
  //  inputString.reserve(200);
  establishContact();  // send a byte to establish contact until receiver responds
}


void onSendTemps() {
  int tempValue = 123;
  Serial.print(kSendTemps);
  Serial.print(",");
  Serial.println(tempValue);  
}

//void setLED(){
//  char* uuid = cmdMessenger.readStringArg();
//  int ledStatus = cmdMessenger.readInt16Arg();
//
//  digitalWrite(LED_PIN, ledStatus);
//
//  Serial.print(uuid);
//  Serial.print(",");
//  Serial.println(ledStatus);
//}

void loop()
{
  cmdMessenger.feedinSerialData();

  delay(1000);//temporary for testing

}
```

**Comment by L-K-Mist** [comment]
Oops, please ignore above arduino code (that was mid-tweaking) 

Here is the version that compiles:
```
#include <CmdMessenger.h>

CmdMessenger cmdMessenger = CmdMessenger(Serial);

enum
{
  kSendTemps,

};

void establishContact() {
  while (Serial.available() <= 0) {
    Serial.println("A1");   // send an initial string
    delay(300);
  }
}

void cmdSetup() {
  cmdMessenger.printLfCr();
  cmdMessenger.attach(kSendTemps, onSendTemps);
}

void onSendTemps() {
  int tempValue = 123;
  Serial.print(kSendTemps);
  Serial.print(",");
  Serial.println(tempValue);
}

void commsSetup() {
  Serial.begin(9600);
  //  inputString.reserve(200);
  establishContact();  // send a byte to establish contact until receiver responds
}

void setup()
{
  commsSetup();
  // Adds newline to every command
  cmdSetup();

}

void loop()
{
  cmdMessenger.feedinSerialData();

  delay(1000);//temporary for testing

}
```

PS I do foresee an arduino library to match serial-synapse

**Comment by hlfshell** [comment]
First off, note that surrounding text with three back ticks ` will create a much easier to read code block:
```
Like so
```

I modified your prior comments to make it easier to read.

The error is being thrown because the `arduino.getTemps();` function needs a callback.

When a serial-synapse function is called, it is asynchronously firing the command. The callback it is expecting to be inside that function is executed only when (if) the arduino responds to that particular call.

To see what I mean, try
```
arduino.getTemps( (err, temp)=> {

    if(err) console.log("Something went wrong", err);
    else console.log("The temperature is", temp);

});
```

**Comment by L-K-Mist** [comment]
Thanks for the guidance, will execute during the day.

I'm a solo, small-town novice, so still gotta get the hang things - like
I'm guessing Issue Reporting is the wrong place for a query like mine?

**Comment by hlfshell** [comment]
It just sounds like you gotta play with node a bit more and get a hang on things. I'd just read up more tutorials on node in the meantime until you get a good handle on the language.
